Add null-check to handle menu entries without npcs
java.lang.NullPointerException: Cannot invoke "net.runelite.api.NPC.getId()" because "npc" is null
        at net.runelite.client.game.NpcUtil.isDying(NpcUtil.java:67)
        at com.betternpchighlight.managers.MenuManager.resolveNpcActionColor(MenuManager.java:101)
        at com.betternpchighlight.managers.MenuManager.colorizeNpcMenuEntry(MenuManager.java:89)
        at com.betternpchighlight.managers.MenuManager.onMenuEntryAdded(MenuManager.java:73)
        at com.betternpchighlight.BetterNpcHighlightPlugin.onMenuEntryAdded(BetterNpcHighlightPlugin.java:161)